### Test Flask Backend is Running
GET http://localhost:5001/

###

### Get All Users (should be empty initially)
GET http://localhost:5001/api/users

###

### Add a New User
POST http://localhost:5001/api/users
Content-Type: application/json

{
  "first_name": "Daivion",
  "last_name": "Brooks",
  "email": "dlb22e@fsu.edu",
  "password": "mypassword123",
  "age": 21,
  "gender": "Male",
  "weight_lbs": 160,
  "height_ft": 6,
  "current_diagnoses": "Has aids",
  "medical_history": "Took aid medicine 3 years ago"
}

###

### Add Another User
POST http://localhost:5001/api/users
Content-Type: application/json

{
  "first_name": "Lebron",
  "last_name": "James",
  "email": "lebronjames@example.com", 
  "password": "password456",
  "age": 45,
  "gender": "Male",
  "height_ft": 7
}

###

### Get All Users Again (should show the users we added)
GET http://localhost:5001/api/users

###

### Test Error - Missing Password (should fail)
POST http://localhost:5001/api/users
Content-Type: application/json

{
  "first_name": "Michael",
  "last_name": "Jordan",
  "email": "michaeljordan@example.com"
}

###

### Test Error - Duplicate Email (should fail)
POST http://localhost:5001/api/users
Content-Type: application/json

{
  "first_name": "Daivion",
  "last_name": "Brooks",
  "email": "dlb22e@fsu.edu",
  "password": "mypassword123",
  "age": 21,
  "gender": "Male",
  "height_ft": 6,
  "medical_history": "Took aid medicine 3 years ago"
}

###

### Add Symptom for User 1
POST http://localhost:5001/api/users/1/symptoms
Content-Type: application/json

{
  "severity": 10,
  "type_of_symptom": "blood",
  "weight_lbs": 93.0,
  "notes": "almost died again"
}

###

### Get Symptoms for User 1
GET http://localhost:5001/api/users/1/symptoms

###

### Get All Users Again (should show the users we added with symptoms)
GET http://localhost:5001/api/users
###

### Add Food Log for User 1
POST http://localhost:5001/api/users/1/food-logs
Content-Type: application/json

{
  "breakfast": "Oatmeal with berries",
  "lunch": "Chicken salad",
  "dinner": "Grilled salmon",
  "total_calories": 1800,
  "notes": "Felt good today"
}

###

## Get Food_logs for User 1
GET http://localhost:5001/api/users/1/food-logs

###


### Get All Users Again (should show the users we added with symptoms and food logs)
GET http://localhost:5001/api/users

###