version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ma_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ma_user}
      POSTGRES_DB: ${POSTGRES_DB:-med_assist_db}
    ports:
      - "5433:5432"          # host:container
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: